### ISSUE TITLE
Add handler for forward slash in file.name

### ISSUE THREAD

**Issue by JakeComing** [DrauzJu/gdrive-sync#2]

**Comment by JakeComing** [comment]
Great tool you've built here! I'm currently modifying it to handle Google Drive documents. I've gotten that portion working, but as the subject line states, there's an issue when the file in question has a forward slash. I think it has something to do with the file being seen as part of a directory stack. 

I'll be sure to update here if I figure it out!

**Comment by DrauzJu** [comment]
Hi, thanks for using it! You may be right, e.g. here the path is split by forward slash: https://github.com/DrauzJu/gdrive-sync/blob/e9529da3d9ca4b6ca810d3e7edee04fb1f03eade/lib/Config.js#L84

I'll also take a look at it and try to figure it out

**Comment by JakeComing** [comment]
Thanks for the response, I was able to get around this by adding the following snippet to the end of listFiles(), this works in my use case but maybe not for everyone. 

`        for(let i=0;i<response.data.files.length;i++) {
            if (response.data.files[i].name.includes('/')) {
                response.data.files[i].name = response.data.files[i].name.replace('/','SLASH');
                console.log(response.data.files);
            }
        }
   return response.data;`

I'll be publishing my code on a fork I made once it's ready.

**Comment by DrauzJu** [comment]
Hi, I did some further research on this topic. On most filesystems (and according to [this post](https://stackoverflow.com/questions/9847288/is-it-possible-to-use-in-a-filename), linux in general), having a forward slash in a file name is not allowed, so I'll close the issue.
Nevertheless, I'm looking forward for a PR dealing with Google Drive Documents :)
